services:
  reverse_proxy:
    build: ./reverse-proxy
    container_name: last_dime_reverse_proxy
    volumes:
      - ./reverse-proxy/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx/log/nginx:/var/log/nginx
    ports:
      - 7999:7999
    networks:
      - network

  db:
    image: postgres:18.1-alpine
    container_name: last_dime_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "7998:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - network
  
  dba:
    image: clidey/whodb:0.81.0
    container_name: last_dime_dba
    expose:
      - 8080
    networks:
      - network

networks:
  network:
    driver: bridge
